// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XWPg8XnWLvDj0KyUck9AgZkqeeX2J3Q',
    appId: '1:96149180770:web:8e551b2bff1fbe5a041c3b',
    messagingSenderId: '96149180770',
    projectId: 'flutter-firebase-flow',
    authDomain: 'flutter-firebase-flow.firebaseapp.com',
    storageBucket: 'flutter-firebase-flow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVbxGoMpln58FxCyPX-cVA9pj1WXcRfJk',
    appId: '1:96149180770:android:e858cc3781c114f9041c3b',
    messagingSenderId: '96149180770',
    projectId: 'flutter-firebase-flow',
    storageBucket: 'flutter-firebase-flow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdVBjkDkXTVuPRTJgoEabJCL82nIGX4A',
    appId: '1:96149180770:ios:0da414ce89700306041c3b',
    messagingSenderId: '96149180770',
    projectId: 'flutter-firebase-flow',
    storageBucket: 'flutter-firebase-flow.appspot.com',
    iosClientId: '96149180770-g5cfjdjcp1i8t2ii62qs0i6lbm58vt30.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );
}
